name: Build & Deploy to Firebase Hosting (merge)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  FIREBASE_CLI_PREVIEWS: hostingchannels

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Downgrade npm to v9 (work-around dla Rollupa)
        run: npm install -g npm@9

      - name: Install dependencies
        run: npm ci

      - name: Force-install brakującej binarki Rollupa
        run: npm i --ignore-scripts --force @rollup/rollup-linux-x64-gnu@7.2.8

      - name: Build project
        run: npm run build

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
          projectId: your-firebase-project-id
          channelId: ${{ github.event_name == 'pull_request' && format('pr-{0}', github.event.number) || 'live' }}
        env:
          VITE_GOOGLE_API: ${{ secrets.VITE_GOOGLE_API }}